# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/34a111f1-beb0-4c76-832d-b2b8fbeca9c3";
      fsType = "btrfs";
      options = [ "subvol=@/.nixos" ];
    };

  boot.initrd.luks.devices."nvme0n1p3_crypt".device = "/dev/disk/by-uuid/7533314a-67e5-421c-82ea-40ffb0c52839";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F04C-A48D";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/34a111f1-beb0-4c76-832d-b2b8fbeca9c3";
      fsType = "btrfs";
      options = [ "subvol=@/.nixos/home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/34a111f1-beb0-4c76-832d-b2b8fbeca9c3";
      fsType = "btrfs";
      options = [ "subvol=@/.nixos/nix" ];
    };

  fileSystems."/etc" =
    { device = "/dev/disk/by-uuid/34a111f1-beb0-4c76-832d-b2b8fbeca9c3";
      fsType = "btrfs";
      options = [ "subvol=@/.nixos/etc" ];
    };


}
