# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "hisi_sas_v3_hw" "ahci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "radeon.si_support=0" "amdgpu.si_support=1" ];

  services.xserver.videoDrivers = [ "amdgpu" ];
  hardware.enableRedistributableFirmware = true;
  hardware.opengl = {
    enable = true;
    package = (pkgs.mesa.override {
      galliumDrivers = [ "r600" "radeonsi" "nouveau" "virgl" "swrast" ];
      vulkanDrivers = [ "amd" "swrast" ];
    }).drivers;
  };

  nix.settings.cores = 4;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f3fec70f-aa77-4350-9cd0-37c83452f429";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2B8E-6633";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/f3fec70f-aa77-4350-9cd0-37c83452f429";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@nix" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c8497b5e-97ce-4525-a51f-89917c4ca662";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@home" "compress=zstd" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e357e8ab-ea6d-4d6a-973e-67c5cf4d3bca"; }
    ];

  boot.kernelPackages = pkgs.linuxPackages_5_10;

}
